# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Overpurple Gatsby Publish

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
        node-version: ${{ matrix.node-version }}
        access-token: ${{ secrets.OVERPURPLE }}
        deploy-branch: master
        gatsby-args: --prefix-paths
        develop-repo: overpurple.io
        
