# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Overpurple Gatsby Publish

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: enriikke/gatsby-gh-pages-action@v2
      with:
        access-token: ${{ secrets.OVERPURPLE }}
        deploy-branch: gh-pages
        gatsby-args: --prefix-paths
        